/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TerraLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUTHORITY_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "REGISTRAR_ROLE"
      | "addRegistrar"
      | "approveTransfer"
      | "cancelTransfer"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "nextPropertyId"
      | "properties"
      | "registerProperty"
      | "removeRegistrar"
      | "renounceRole"
      | "requestTransfer"
      | "revokeRole"
      | "supportsInterface"
      | "transferRequests"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PropertyRegistered"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TransferApproved"
      | "TransferRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUTHORITY_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRAR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPropertyId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "properties",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProperty",
    values: [AddressLike, string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeRegistrar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestTransfer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferRequests",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUTHORITY_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRAR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextPropertyId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeRegistrar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferRequests",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    oldOwner: AddressLike,
    newOwner: AddressLike
  ];
  export type OutputTuple = [
    propertyId: bigint,
    oldOwner: string,
    newOwner: string
  ];
  export interface OutputObject {
    propertyId: bigint;
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyRegisteredEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    owner: AddressLike,
    location: string,
    area: string,
    propertyType: string
  ];
  export type OutputTuple = [
    propertyId: bigint,
    owner: string,
    location: string,
    area: string,
    propertyType: string
  ];
  export interface OutputObject {
    propertyId: bigint;
    owner: string;
    location: string;
    area: string;
    propertyType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferApprovedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    owner: AddressLike,
    buyer: AddressLike
  ];
  export type OutputTuple = [propertyId: bigint, owner: string, buyer: string];
  export interface OutputObject {
    propertyId: bigint;
    owner: string;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRequestedEvent {
  export type InputTuple = [
    propertyId: BigNumberish,
    owner: AddressLike,
    buyer: AddressLike
  ];
  export type OutputTuple = [propertyId: bigint, owner: string, buyer: string];
  export interface OutputObject {
    propertyId: bigint;
    owner: string;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TerraLedger extends BaseContract {
  connect(runner?: ContractRunner | null): TerraLedger;
  waitForDeployment(): Promise<this>;

  interface: TerraLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUTHORITY_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  REGISTRAR_ROLE: TypedContractMethod<[], [string], "view">;

  addRegistrar: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  approveTransfer: TypedContractMethod<
    [_propertyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  cancelTransfer: TypedContractMethod<
    [_propertyId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  nextPropertyId: TypedContractMethod<[], [bigint], "view">;

  properties: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, boolean] & {
        propertyId: bigint;
        owner: string;
        location: string;
        area: string;
        propertyType: string;
        isRegistered: boolean;
      }
    ],
    "view"
  >;

  registerProperty: TypedContractMethod<
    [
      _propertyOwner: AddressLike,
      _location: string,
      _area: string,
      _propertyType: string
    ],
    [void],
    "nonpayable"
  >;

  removeRegistrar: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestTransfer: TypedContractMethod<
    [_propertyId: BigNumberish, _buyer: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { buyer: string; pending: boolean }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUTHORITY_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "REGISTRAR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addRegistrar"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveTransfer"
  ): TypedContractMethod<[_propertyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelTransfer"
  ): TypedContractMethod<[_propertyId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextPropertyId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "properties"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, boolean] & {
        propertyId: bigint;
        owner: string;
        location: string;
        area: string;
        propertyType: string;
        isRegistered: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProperty"
  ): TypedContractMethod<
    [
      _propertyOwner: AddressLike,
      _location: string,
      _area: string,
      _propertyType: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeRegistrar"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestTransfer"
  ): TypedContractMethod<
    [_propertyId: BigNumberish, _buyer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[string, boolean] & { buyer: string; pending: boolean }],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyRegistered"
  ): TypedContractEvent<
    PropertyRegisteredEvent.InputTuple,
    PropertyRegisteredEvent.OutputTuple,
    PropertyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TransferApproved"
  ): TypedContractEvent<
    TransferApprovedEvent.InputTuple,
    TransferApprovedEvent.OutputTuple,
    TransferApprovedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRequested"
  ): TypedContractEvent<
    TransferRequestedEvent.InputTuple,
    TransferRequestedEvent.OutputTuple,
    TransferRequestedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(uint256,address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PropertyRegistered(uint256,address,string,string,string)": TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;
    PropertyRegistered: TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TransferApproved(uint256,address,address)": TypedContractEvent<
      TransferApprovedEvent.InputTuple,
      TransferApprovedEvent.OutputTuple,
      TransferApprovedEvent.OutputObject
    >;
    TransferApproved: TypedContractEvent<
      TransferApprovedEvent.InputTuple,
      TransferApprovedEvent.OutputTuple,
      TransferApprovedEvent.OutputObject
    >;

    "TransferRequested(uint256,address,address)": TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;
    TransferRequested: TypedContractEvent<
      TransferRequestedEvent.InputTuple,
      TransferRequestedEvent.OutputTuple,
      TransferRequestedEvent.OutputObject
    >;
  };
}
